### PR TITLE
Generate bindings (missing include paths) for FEM

### PR DESCRIPTION
**Pull request by lulf**

### CODE REVIEW

**Comment by alexmoon** [comment]
Are you using the FEM APIs?

**Comment by lulf** [comment]
@alexmoon Will be soon, but I've turned to work on a flash driver using timeslots first, so there is no urge to merge this yet.

**Comment by alexmoon** [comment]
I think the common includes should be split out from the impl-specific ones. Perhaps there should be a `fem` feature that the others activate that triggers inclusion of all the common `fem` headers?

**Comment by alexmoon** [comment]
I was thinking you could theoretically provide your own FEM library implementation if you had a different FEM you wanted to support. Not sure if that's possible, though. Mostly, I just think the common headers obscure the actual differences between the FEM impls.

**Comment by lulf** [comment]
Makes sense, let me know if the last change matches your thinking.

**Review by alexmoon — APPROVED** [review]

**Pull request merged**
